### ISSUE TITLE
Installing Heatplot on a computer without internet connection

### ISSUE THREAD

**Issue by JakobWegmann** [benjann/heatplot#2]
I try to install heatplot on a computer (Stata 16.0) without internet connection. To do so, I downloaded the three Zip Files of (heatplot, colorpsace, palettes) from the respective git repos, brought the files to the computer without internet connection and copied the content of the files to the PLUS folder.
So the ado folders include the following:
ado/plus/c: colorpalette.ado, colorpallette9.ado, colorpsace.pkg, colorspace_cscript.do (and the corresponding sthlp files)
ado/plus/h: heatplot.ado, heatplot.pkg, hexplot.ado (and the corresponding sthlp files)
ado/plus/l: lcolrspace.mlib, linepalette.ado
ado/plus/p: paletttes.pkg
ado/plus/s: symbolpalette.ado

When running heatplot, I have the following error message: 
```
Class ColrSpace undefined
(282 lines skipped)
(error occurred while loading colorpalette.ado)
```
Do you have an idea how to solve this problem?

**Comment by benjann** [comment]
Possibly it will work after restating Stata or after typing `mata mata mlib index`.

However, manual installation by copying files around can be tricky. My advice is to obtain the zipfiles provided at the SSC archive and then follow the installation instructions given therein (see the `readme.txt` within these zipfiles). The zipfiles on SSC have been specifically put together to support installation from a local drive rather than the internet. You can obtain the three zipfiles from the following links:

[colrspace](https://ideas.repec.org/c/boc/bocode/s458597.html)

[heatplot](https://ideas.repec.org/c/boc/bocode/s458598.html)

[palettes](https://ideas.repec.org/c/boc/bocode/s458444.html)

(Click the "Download" tab and then select the zip-file from the list; you only need the zipfile, not the other files.)

Using the example of `colrspace`, the installation instructions are as follows:

1. Download `colrspace.zip`.

2. Unzip `colrspace.zip` into an empty temporary directory on your hard disk (e.g. `c:\temp`).

3. Start Stata and type `net from c:\temp` (substitute `c:\temp` with whatever path you used for the temporary directory).

4. Type `net install colrspace, replace`.

5. Delete the files form the temporary directory.

For the other packages, follow an analogous procedure.

ben

**Comment by JakobWegmann** [comment]
Thank you very much, that was really helpful. Everything is working now, the heatplots are beautiful!

**Comment by benjann** [comment]
perfect
